name = "dynamic-api-mongodb"
type = "javascript"
account_id = "4ca26ecdb0c4f07d9bc0c2aa7f2f206e"
main = "worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_v2"]

[env.production]
name = "dynamic-api-mongodb-prod"
route = "example.com/api/mongodb/*"
zone_id = "YOUR_CLOUDFLARE_ZONE_ID"

[build]
command = "npm run build || echo 'No build script'"
cwd = "."

[env.production.vars]
NODE_ENV = "production"
LOG_LEVEL = "info"
PORT = "8787"
OTP_EMAIL_FROM = "noreply@yourdomain.com"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "your-email@gmail.com"
ALLOWED_ORIGINS = "https://dynamic-api-orpin.vercel.app/"

